### ISSUE TITLE
typeerror in example notebooks

### ISSUE THREAD

**Issue by khunetworking** [geraintpalmer/Ciw-notebooks#3]
solve it

**Comment by drvinceknight** [comment]
Hi, your comment doesn't really set a standard for which the maintainer can find time to assist. I'd suggest this comment be closed and in future if you find issues with the software you describe them in a way that helps the maintainer fix them without spending too much time. I'd suggest reading this about reporting bugs for Open Source Software: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
