### ISSUE TITLE
examples out of date?

### ISSUE THREAD

**Issue by beantowel** [geraintpalmer/Ciw-notebooks#5]
in "Basic Queueing Network.ipynb", the ciw library seems no longer needs key "number_of_nodes" and "number_of_classes". By the way, i couldn't directly pass the parameters in a dic like this 
`N = ciw.create_network(params)`
 instead i have to use 
`N = ciw.create_network(**params)`
can someone tell the reasons?

**Comment by geraintpalmer** [comment]
Hi @beantowel yes the notebooks are out of date. Will try to update them as soon as possible, thanks for noticing!

In an older version of Ciw the `ciw.create_network` function took in one argument for a parameters dictionary. Now it takes each key of that dictionary as separate arguments.
Using `N = ciw.create_network(**params)` you are unpacking those dictionary keys into separate arguments for the function.

Hope that helps!
